services:
  microservice:
    build:
      context: .
      dockerfile: ./microservice.Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - PGDATABASE=${PGDATABASE}
    volumes:
      - .:/usr/src/app
    command: air . -b 0.0.0.0
  db:
    build:
      context: .
      dockerfile: ./db.Dockerfile
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - DATABASE_HOST=${PGHOST}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
