services:
  microservice:
    build:
      context: .
      dockerfile: ./microservice.Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
      - PGHOST=${DB_HOST}
      - PGDATABASE=${DB_NAME}
    volumes:
      - .:/usr/src/app
    command: air . -b 0.0.0.0
  db:
    build:
      context: .
      dockerfile: ./db.Dockerfile
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
